// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idsjiwzdbkjhcwundudp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkc2ppd3pkYmtqaGN3dW5kdWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzgwMzcsImV4cCI6MjA2MjkxNDAzN30.IulnrGc4iddAdWN2_KGwpztJRkNyitz5qPXonxtZNiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);